#!/usr/bin/env python2

import time
import platform

# Simple script to test CI build pipeline
print 'Date:\t\t', time.strftime("%d.%m.%Y %H:%M")
print 'Distrib:\t', ' '.join(platform.linux_distribution())
